apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
spec:
  destination:
    namespace: app
    server: https://kubernetes.default.svc
  source:
    path: .
    repoURL: https://github.com/AbhiramVijayan/argocd
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      enabled: true
