apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2026-10-03T10:18:46Z"
  generation: 1
  labels:
    app: nginx
  name: nginx
  namespace: argocd
  resourceVersion: "2712"
  uid: 806f1b0c-c750-4501-a705-021e3061b1a0
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nginx
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginx
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
